version: "3.8"
services:
  postgresql:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "profile"
    volumes:
      - /Users/khanh/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  server:
    depends_on:
      - postgresql
    build:
      context: .
      dockerfile: Dockerfile

  spring_boot_docker_compose:
    image: spring-boot-docker-compose
    container_name: spring_boot_docker_compose
    depends_on:
      - postgresql
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "123"
      DATABASE_HOST: "postgresql"
      DATABASE_NAME: "profile"
      DATABASE_PORT: 5432
    ports:
      - 8091:8091
    networks:
      - default

networks:
  huongdanjava:
    driver: bridge