app:
  name: Tech Interface - Swagger and Profiles Tutorial


mailServer:
  host: smtp.gmail.com
  port: 587
  email: hieunmhe140582@fpt.edu.vn
  password: Vietnam123456789
  protocol: smtp
  isSSL: false

minio:
  port: 9000
  endpoint: 103.176.110.28
  url: http://103.176.110.28:9000
  ssl: false
  access:
    name: minio
    secret: minio123
  bucket: images
  default:
    folder: /

spring:
  datasource:
    spring.datasource.url=${JDBC_DATABASE_URL:}
    spring.datasource.username=${JDBC_DATABASE_USERNAME:}
    spring.datasource.password=${JDBC_DATABASE_PASSWORD:}
    spring.datasource.driverClassName=${JDBC_DATABASE_DRIVER:}